mainapp/urls.py
from django.urls import path
from . import views

app_name = 'mainapp'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('about', views.about_view, name='about'),
    path('causes', views.causes_view, name='causes'),
    path('blog', views.blog_view, name='blog'),
    path('volunteer', views.volunteer_view, name='volunteer'),
    path('impact', views.impact_view, name='impact'),
    path('gallery', views.gallery_view, name='gallery'),
    path('staff', views.staff_view, name='staff'),
    path('contact', views.contact_view, name='contact'),

]

pamojaproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
]

mainapp/models.py
from django.db import models

# Create your models here.

mainapp/views.py
from django.shortcuts import render

def home_view(request):
    return render(request, 'mainapp/index.html')

def about_view(request):
    return render(request, 'mainapp/about.html')

def causes_view(request):
    return render(request, 'mainapp/causes.html')

def blog_view(request):
    return render(request, 'mainapp/blog.html')

def volunteer_view(request):
    return render(request, 'mainapp/volunteer.html')

def impact_view(request):
    return render(request, 'mainapp/impact.html')

def gallery_view(request):
    return render(request, 'mainapp/gallery.html')

def staff_view(request):
    return render(request, 'mainapp/staff.html')

def contact_view(request):
    return render(request, 'mainapp/contact.html')

mainapp/templates/mainapp/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Pamoja CBO</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="../../../fonts.googleapis.com/cssa1c0.css?family=Overpass:300,400,500|Dosis:400,700" rel="stylesheet">
    <!-- <link rel="stylesheet" href="css/stuff.css" />
<link rel="stylesheet" href="css/stuff2.css" /> -->
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
<link rel="stylesheet" href="{% static 'css/stuff3.css' %}" />
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="{% static 'css/owl-carousel.css' %}">
<link rel="stylesheet" href="{% static 'css/datepicker.css' %}">
<link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/solid.css"
        integrity="sha384-Tv5i09RULyHKMwX0E8wJUqSOaXlyu3SQxORObAI08iUwIalMmN5L6AvlPX2LMoSE" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/fontawesome.css"
        integrity="sha384-jLKHWM3JRmfMU0A5x5AkjWkw/EYfGUAGagvnfryNV3F9VqM98XiIH7VBGVoxVSc7" crossorigin="anonymous" />

    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@500&display=swap" rel="stylesheet">
    <script
        nonce="99bc3aeb-c369-4673-a964-210f658c954f">(function (w, d) { !function (a, e, t, r) { a.zarazData = a.zarazData || {}, a.zarazData.executed = [], a.zaraz = { deferred: [] }, a.zaraz.q = [], a.zaraz._f = function (e) { return function () { var t = Array.prototype.slice.call(arguments); a.zaraz.q.push({ m: e, a: t }) } }; for (const e of ["track", "set", "ecommerce", "debug"]) a.zaraz[e] = a.zaraz._f(e); a.addEventListener("DOMContentLoaded", (() => { var t = e.getElementsByTagName(r)[0], z = e.createElement(r), n = e.getElementsByTagName("title")[0]; for (n && (a.zarazData.t = e.getElementsByTagName("title")[0].text), a.zarazData.x = Math.random(), a.zarazData.w = a.screen.width, a.zarazData.h = a.screen.height, a.zarazData.j = a.innerHeight, a.zarazData.e = a.innerWidth, a.zarazData.l = a.location.href, a.zarazData.r = e.referrer, a.zarazData.k = a.screen.colorDepth, a.zarazData.n = e.characterSet, a.zarazData.o = (new Date).getTimezoneOffset(), a.zarazData.q = []; a.zaraz.q.length;) { const e = a.zaraz.q.shift(); a.zarazData.q.push(e) } z.defer = !0; for (const e of [localStorage, sessionStorage]) Object.keys(e).filter((a => a.startsWith("_zaraz_"))).forEach((t => { try { a.zarazData["z_" + t.slice(7)] = JSON.parse(e.getItem(t)) } catch { a.zarazData["z_" + t.slice(7)] = e.getItem(t) } })); z.referrerPolicy = "origin", z.src = "../../cdn-cgi/zaraz/sd0d9.js?z=" + btoa(encodeURIComponent(JSON.stringify(a.zarazData))), t.parentNode.insertBefore(z, t) })) }(w, d, 0, "script"); })(window, document);</script>
</head>
<body>
  <!-- <nav class="navbar navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
      <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:home' %}">
            <img class="img-fluid" src="{% static 'images/pamojawhite.png' %}" alt="logo"
              style="width:300px;height:auto">
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
              aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="oi oi-menu"></span> Menu
          </button>
          <div class="collapse navbar-collapse" id="ftco-nav">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="{% url 'mainapp:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:about' %}" class="nav-link">About Us</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:causes' %}" class="nav-link">Causes</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:blog' %}" class="nav-link">Blog</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:volunteer' %}" class="nav-link">Volunteer</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:gallery' %}" class="nav-link">Gallery</a></li>
                <li class="nav-item active"><a href="{% url 'mainapp:contact' %}" class="nav-link">Contact</a></li>
              </ul>
          </div>
      </div>
  </nav> -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:home' %}">
            <img class="img-fluid" src="{% static 'images/home/PamojaPamoja.png' %}" alt="logo"
                style="width:180px;height:auto">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a href="{% url 'mainapp:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:about' %}" class="nav-link">About Us</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                        aria-haspopup="true" aria-expanded="false">What We Do</a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'mainapp:causes' %}" style="font-size: 14px;">Causes</a>
                        <a class="dropdown-item" href="{% url 'mainapp:impact' %}" style="font-size: 14px;">Our
                            Impact</a>
                    </div>
                </li>
                <li class="nav-item"><a href="{% url 'mainapp:blog' %}" class="nav-link">Blog</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:volunteer' %}" class="nav-link">Volunteer</a></li>
                <li class="nav-item"><a href="{% url 'mainapp:gallery' %}" class="nav-link">Gallery</a></li>
                <li class="nav-item active"><a href="{% url 'mainapp:contact' %}" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>
  <!-- <div>
      <div class="">
          <div class=""
              style="background-image: url('../../static/images/home/bg_5.jpg'); height:550px;background-position: center center;">
              <div class=" container"
                  style="color:#fff;font-size:15px;left:15px;right:15px;text-align:left;text-shadow:none;top:90%;margin-top:-180px;padding-top:380px">
                  <h6 class="animated fadeIn" style="font-size: 40px;font-weight: bold;">Volunteer or Partner with Us
                  </h6>
              </div>
          </div>
      </div>
  </div> -->
  <br><br><br><br><br><br><br><br>
  <h1 class="text-center">DON'T BE SHY. <span style="color:#288e19">COME SAY HI!</span></h1>
  <br><br><br><br>
  <div class="container">
    <div class="row">
        <div class="col-md-5">
            <form>
                <div class="form-group">
                    <label for="exampleInputEmail1">Name</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Email</label>
                    <input type="email" class="form-control">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Subject</label>
                    <input type="text" class="form-control">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Your Message</label>
                    <textarea name="" class="form-control" id="" cols="30" rows="5"></textarea>
                </div>
                <button type="submit" class="btn btn-primary" style="padding:9px 15px;border-radius:9px;">Submit</button>
            </form>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-5">
            <img src="{% static 'images/home/contactill.png' %}" class="img-fluid" alt="">
        </div>
    </div>
    <br><br><br>
    <div class="row">
        <div class="col-md-4">
            <img class="img-fluid" src="{% static 'images/home/PamojaPamoja.png' %}" alt="logo"
                    style="width:300px;height:auto">
        </div>
        <div class="col-md-4">
            <h3 style="font-weight: bold;"><img src="https://img.icons8.com/fluency/30/000000/worldwide-location.png"/>&nbsp;&nbsp;Our Offices:</h3>
            <ul class = "list-unstyled">
                <li>1. Off Kisumu-Bondo Road, Near Holo Market</li>
                <li>2. Off Kisumu-Busia Road, near Daraja Mbili market</li>
            </ul>
        </div>
        <div class="col-md-4">
            <p><img src="https://img.icons8.com/color/30/000000/ringing-phone.png"/>&nbsp;&nbsp;&nbsp;Phone: <b>+254 7 801 160 000</b></p>
            <p><img src="https://img.icons8.com/color/30/000000/apple-mail.png"/>&nbsp;&nbsp;&nbsp;Email: <b>info@pamojapamoja.org</b></p>
        </div>
    </div>
</div>
<br><br><br>

</body>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script
  src="{% static 'js/jquery-migrate-3.0.1.min.js%2bpopper.min.js%2bbootstrap.min.js%2bjquery.easing.1.3.js.pagespeed.jc.UfoK2ZK92N.js' %}"></script>
<script>eval(mod_pagespeed__5Yoqz5Pwn);</script>
<script>eval(mod_pagespeed_KZlkIIJlO3);</script>
<script>eval(mod_pagespeed_QWr0uXaXaU);</script>
<script>eval(mod_pagespeed_pnj9KVQygE);</script>
<script
  src="{% static 'js/jquery.waypoints.min.js%2bjquery.stellar.min.js%2bowl.carousel.min.js%2bjquery.magnific-popup.min.js.pagespeed.jc.CE0oN1Bwzq.js' %}"></script>
<script>eval(mod_pagespeed_6t$u8$1XBS);</script>
<script>eval(mod_pagespeed_YhLXOfd9vP);</script>
<script>eval(mod_pagespeed_xdKIJPVMXB);</script>
<script>eval(mod_pagespeed_hFobBDlaRU);</script>
<script src="js/bootstrap-datepicker.js"></script>
<script
  src="{% static 'js/jquery.fancybox.min.js%2baos.js%2bjquery.animateNumber.min.js%2bgoogle-map.js%2bmain.js.pagespeed.jc.nGnVN_nqcj.js' %}"></script>
<script>eval(mod_pagespeed_bPMfuRRc$t);</script>
<script>eval(mod_pagespeed_327Vziik2k);</script>
<script>eval(mod_pagespeed_dFb3UKP9Kq);</script>
<script
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&amp;sensor=false"></script>
<script>eval(mod_pagespeed_c7BIxLN_4h);</script>
<script>eval(mod_pagespeed_HdekMp55Bh);</script>

</body>


</html>

mainapp/templates/mainapp/nav.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'mainapp:home' %}">
        <img class="img-fluid" src="{% static 'images/home/PamojaPamoja.png' %}" alt="logo"
          style="width:180px;height:auto">
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active"><a href="{% url 'mainapp:home' %}" class="nav-link">Home</a></li>
          <li class="nav-item"><a href="{% url 'mainapp:about' %}" class="nav-link">About Us</a></li>
          <li class="nav-item"><a href="{% url 'mainapp:causes' %}" class="nav-link">Causes</a></li>
          <li class="nav-item"><a href="{% url 'mainapp:blog' %}" class="nav-link">Blog</a></li>
          <li class="nav-item"><a href="{% url 'mainapp:volunteer' %}" class="nav-link">Volunteer</a></li>
          <li class="nav-item"><a href="{% url 'mainapp:gallery' %}" class="nav-link">Gallery</a></li>
          <li class="nav-item"><a href="{% url 'mainapp:contact' %}" class="nav-link">Contact</a></li>
        </ul>
      </div>
    </div>
    
  </nav>